
name = "feathered"
compatibility_date = "2026-01-14"
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "DT"
database_name = "feathered"
database_id = "78ab2b7fc1c115c69e62ef876c825f44"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "feathered"
